### PR TITLE
Handle empty issue body when removing HTML

### LINKED ISSUE #31: Sync fails if GitHub Issue has an empty `body`
<sub>[Discuss in #**issue-31--sync-fails-if-github-issue-has-an-empty-body**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C02G0HZ0JUC)</sub>

**Describe the bug**
When parsing the issue body in the `removeHTML` function, an exception is raised if the issue body is empty: `Cannot read property 'replace' of null`

**To Reproduce**
1. Create an issue with no body (in a repo with the action wired up)
2. The action will fail and the issue will not be synced to Notion

**Expected behavior**
The issue is pushed to Notion with the `body` field empty

**Screenshots**
image

### PR DESCRIPTION
**Pull request by conarro**
If an issue is created with an empty body, the action failed when calling `replace` on `null`. This PR updates the `removeHTML` function to return an empty string if the `text` argument is `null`.

Fixes #31

### CODE REVIEW

File: src/action.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ import type {InputPropertyValueMap} from '@notionhq/client/build/src/api-endpoin
 import {SelectPropertyValue} from '@notionhq/client/build/src/api-types';
 
 function removeHTML(text: string): string {
```
Comment (rr-codes) [inline src/action.ts:9]:
```suggestion
function removeHTML(text?: string): string {
```

**Review by rr-codes — CHANGES_REQUESTED** [review]

**Comment by rr-codes** [comment]
Thanks @conarro! I added a few comments. Would you also mind creating a corresponding issue for this as well please? Thanks!

**Comment by conarro** [comment]
@rr-codes filed an issue here #31. Just applied your suggestions, let me know if you want me to squash or anything!

**Review by marissamarym — APPROVED** [review]
LGTM
